export const HORSE_NAMES = [
  'Max Verstappen',
  'Lewis Hamilton',
  'Charles Leclerc',
  'Lando Norris',
  'Carlos Sainz',
  'George Russell',
  'Sergio Perez',
  'Fernando Alonso',
  'Oscar Piastri',
  'Pierre Gasly',
  'Esteban Ocon',
  'Alex Albon',
  'Yuki Tsunoda',
  'Valtteri Bottas',
  'Zhou Guanyu',
  'Nico Hulkenberg',
  'Kevin Magnussen',
  'Daniel Ricciardo',
  'Lance Stroll',
  'Logan Sargeant',
];

export const HORSE_COLORS = [
  { name: 'Crimson', value: '#d64c4c' },
  { name: 'Coral', value: '#f07167' },
  { name: 'Amber', value: '#f4a261' },
  { name: 'Saffron', value: '#e9c46a' },
  { name: 'Olive', value: '#8fb339' },
  { name: 'Emerald', value: '#2a9d8f' },
  { name: 'Teal', value: '#2c7da0' },
  { name: 'Blue', value: '#3a86ff' },
  { name: 'Indigo', value: '#5a4fcf' },
  { name: 'Violet', value: '#7b2cbf' },
  { name: 'Plum', value: '#9d4edd' },
  { name: 'Rose', value: '#f72585' },
  { name: 'Brick', value: '#b23a48' },
  { name: 'Copper', value: '#c97c5d' },
  { name: 'Sand', value: '#d9ae8b' },
  { name: 'Moss', value: '#6b8f71' },
  { name: 'Forest', value: '#386641' },
  { name: 'Slate', value: '#577590' },
  { name: 'Steel', value: '#3d5a80' },
  { name: 'Jet', value: '#2f2f2f' },
];
